### ISSUE TITLE
不太明白这个的作用是什么

### ISSUE THREAD

**Issue by 1055169799** [pcrbot/remake_setting#1]
好像只是发一张设定图，没有后续的延续和结局，有点懵

**Comment by chu3** [comment]
可能原先描述中的“人生重开”字眼会导致误以为该插件玩法预期类似，相比之下该插件并没有给出“故事线”，而是让使用者通过给予的人设进行联想，并且还提供了分数来创造更简单直接的玩法（图一乐

-    已在最近的更新中更改了插件名及描述
